### ISSUE TITLE
Just to let you know I run into this issue

### ISSUE THREAD

**Issue by domainController** [luciopaiva/youtube-list-channel-videos#2]
kami@tumult:~/Documents/Hacking YouTube/youtube-list-channel-videos-master$ node list-videos UCVImyGhRATNFGPmJfxaq1dw
/home/kami/Documents/Hacking YouTube/youtube-list-channel-videos-master/list-videos.js:52
            if (!configFile?.["apiKey"]) {
                            ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
======================================================
i then removed the dot and question mark and run in to another similar parsing issue 20 lines later
======================================================
kami@tumult:~/Documents/Hacking YouTube/youtube-list-channel-videos-master$ node list-videos UCVImyGhRATNFGPmJfxaq1dw
/home/kami/Documents/Hacking YouTube/youtube-list-channel-videos-master/list-videos.js:76
            const data = result?.data;
                                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
kami@tumult:~/Documents/Hacking YouTube/youtube-list-channel-videos-master$

**Comment by luciopaiva** [comment]
Hey @kevin-garnette,

The `?.` you saw is the optional chaining operator:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

It is a relatively recent addition to JavaScript, so you're probably running a browser that offers no support yet. [Here](https://caniuse.com/mdn-javascript_operators_optional_chaining) is the list of supported browsers.

![image](https://user-images.githubusercontent.com/6631859/108627945-f6fdd200-744f-11eb-865c-191bee02af2b.png)

All major browsers currently support it, so it may be just a matter of updating the version you're using (or changing browsers). Of course, it that's not an option, I recommend you fork this repo and replace the optional chaining operator with the old way of doing it. You could also use something like Babel to convert it to ES5, so you can develop using the latest JavaScript features.

Hope it helped!

I'll go ahead and close it as a non-issue, but please feel free to continue the discussion and I'll be glad to answer any other questions.
