### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by Bagunda** [luciopaiva/youtube-list-channel-videos#5]
```
root@shururik:~/youtube-list-channel-videos# node list-videos vladandnikirus
/root/youtube-list-channel-videos/list-videos.js:52
            if (!configFile?.["apiKey"]) {
                            ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

```
root@shururik:~/youtube-list-channel-videos# node list-videos PLPiRgrwSxW6ToLaBeBEQv_1OMUVEzrypx
/root/youtube-list-channel-videos/list-videos.js:52
            if (!configFile?.["apiKey"]) {
                            ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

config.json:
{
  "apiKey": "AIzaSyB-YnE6uy_****wEr5OEEkBQRnC5RRWmHY"
}

https://www.youtube.com/watch?v=ewPIPY1sCbo&list=PLPiRgrwSxW6ToLaBeBEQv_1OMUVEzrypx

**Comment by luciopaiva** [comment]
Hey @Bagunda,

The Nodejs version you are using probably does not support the optional chaining operator (`?.`). I suggest you take a look into the support table [here](https://node.green/#ES2020-features-optional-chaining-operator-----).
